#!/bin/sh

# Installation of powerline fonts as described by:
# https://powerline.readthedocs.org/en/master/installation/linux.html#patched-font-installation

wget https://github.com/ga7g08/dotfiles.gi://github.com/powerline/powerline/raw/develop/font/PowerlineSymbols.otf
wget https://github.com/powerline/powerline/raw/develop/font/10-powerline-symbols.conf

mkdir -p ~/.fonts/
mv PowerlineSymbols.otf ~/.fonts/

fc-cache -vf ~/.fonts/

mkdir -p ~/.config/fontconfig/conf.d
mv 10-powerline-symbols.conf ~/.config/fontconfig/conf.d/
